name: Setup
description: Setup git, node, pnpm and install deps

runs:
  using: "composite"
  steps:
    - name: Git Config
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
      env:
        NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}

    - name: Setup PNPM and Install Deps
      uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: |
          - args: [--frozen-lockfile]