name: Release PR

permissions:
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create PR
        id: changesets
        uses: changesets/action@v1
        with:
          commitMode: 'github-api'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}